version: '3.5'

services:
    postgress:
        container_name: "postgres"
        image: "postgres:12.0"
        ports:
            - "5432:5432"

    redis:
        container_name: redis
        image: redis
        ports:
            - "6379:6379"
        restart: always
